### ISSUE TITLE
Add Mormot as Dependency

### ISSUE THREAD

**Issue by Memnarch** [turric4n/TNs_HTTPRestFramework#1]
Hi,
I have seen your project depends on Mormot. If the currently listed release of mormot is sufficient, please consider adding it as a dependency. Therefore Delphinus can resolve it, when your project is installed.

**Comment by turric4n** [comment]
Hi Memnarch, can you help me with this issue? Can you resolve this dependency in Delphinus.Install.json and make me a pull request?

**Comment by Memnarch** [comment]
Actually this goes into Delphinus.Info.json 😃 
https://github.com/Memnarch/Delphinus/wiki/Delphinus.Info.json

Not at home atm, i'll see what i can do later.  But just to underline my question above: Your project runs with that released version? (or is this working with the head of Mormot, only)

**Comment by turric4n** [comment]
Works with any version of mORMot. Only use bare HTTPServer dependancy

**Comment by Memnarch** [comment]
That is not what dependency means. By adding the dependency, Delphinus can automatically install it. Otherwhise your package is in a nonfunctional state after installation.

**Comment by turric4n** [comment]
Thank you, We removed mORMot dependancies In favour of Indy. Tomorrow I will fix pakage installation.
